### ISSUE TITLE
搭配QChatGPT时提示模型请求失败

### ISSUE THREAD

**Issue by huangzi0721** [RockChinQ/free-one-api#114]
在./data/metadata/llm-models.json已经添加通义千问的模型,qwen和qwen-turbo都试过了,报错如图,llm-models.json配置如图,不知道哪里有问题,求助
<img width="1784" alt="截屏2024-07-17 下午11 34 33" src="https://github.com/user-attachments/assets/6587d46f-2c06-471c-8b39-d3588b222d55">

<img width="1784" alt="截屏2024-07-17 下午11 28 37" src="https://github.com/user-attachments/assets/3d6c6e22-70a3-48a9-b212-04b92552fdc3">

**Comment by RockChinQ** [comment]
foa转出的模型名称都是gpt-3.5-turbo

**Comment by huangzi0721** [comment]
> foa转出的模型名称都是gpt-3.5-turbo

感谢,跑通了
