### ISSUE TITLE
acheong08/ChatGPT  还可以用吗？求教程

### ISSUE THREAD

**Issue by long202258** [RockChinQ/free-one-api#40]
acheong08/ChatGPT  还可以用吗？求教程

**Comment by RockChinQ** [comment]
还可以用的，要在 free-one-api 中配置 acheong08/ChatGPT 渠道，可以按照文档部署 free-one-api，打开管理页面，添加渠道，选择适配器 `acheong08/ChatGPT`，页面中会有个 `Config Comment` 按钮，点击，按照弹出的说明框进行填写即可使用

**Comment by long202258** [comment]
acheong08/ChatGPT&nbsp; 现在还能使用吗？之前有用过现在尝试不成功，能教我一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RockChinQ/free-one-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月16日(星期一) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RockChinQ/free-one-api] acheong08/ChatGPT  还可以用吗？求教程 (Issue #40)





 
还可以用的，要在 free-one-api 中配置 acheong08/ChatGPT 渠道，可以按照文档部署 free-one-api，打开管理页面，添加渠道，选择适配器 acheong08/ChatGPT，页面中会有个 Config Comment 按钮，点击，按照弹出的说明框进行填写即可使用

**Comment by RockChinQ** [comment]
等有空更新个文档吧

**Comment by RockChinQ** [comment]
已更新文档，请查看 https://free-one-api.rockchin.top

**Comment by long202258** [comment]
> 已更新文档，请查看 https://free-one-api.rockchin.top

![image](https://github.com/RockChinQ/free-one-api/assets/97136192/1c96cfab-5b8b-42bc-89b3-1c91bdf965b9)
大哥 不会go语言 这个代理怎么搭建呀  [Docker]也不会用

**Comment by RockChinQ** [comment]
> > 已更新文档，请查看 https://free-one-api.rockchin.top
> 
> ![image](https://github.com/RockChinQ/free-one-api/assets/97136192/1c96cfab-5b8b-42bc-89b3-1c91bdf965b9)
> 大哥 不会go语言 这个代理怎么搭建呀  [Docker]也不会用

看文档吧

**Comment by RockChinQ** [comment]
revChatGPT貌似寄了
