### ISSUE TITLE
现在有一个问题，我在acheong08/ChatGPT渠道中添加了gpt3.5普通账号的accesstoken，但是当我用接口调用gpt-4模型时，也能返回结果

### ISSUE THREAD

**Issue by GuoWeiChi** [RockChinQ/free-one-api#51]
现在有一个问题，我在acheong08/ChatGPT渠道中添加了gpt3.5普通账号的accesstoken，但是当我用接口调用gpt-4模型时，也能返回结果，给某个渠道设置模型嘛，比如gpt3.5的渠道，当接口请求gpt-4渠道的时候不使用设置为3.5的那个渠道

**Comment by RockChinQ** [comment]
目前的渠道都不考虑模型，都会使用逆向库的默认设置来请求模型回复，对于ChatGPT来说就是默认使用GPT-3.5，如果你的账号付费并且可以使用GPT4网页版，你可以根据ChatGPT渠道创建时显示的config comment的内容添加模型参数指定所有通过此渠道的请求都使用指定的模型

**Comment by xiaozhou26** [comment]
> 现在有一个问题，我在acheong08/ChatGPT渠道中添加了gpt3.5普通账号的accesstoken，但是当我用接口调用gpt-4模型时，也能返回结果，给某个渠道设置模型嘛，比如gpt3.5的渠道，当接口请求gpt-4渠道的时候不使用设置为3.5的那个渠道

gpt4free一直用chatbase那个接口，怎么在gpt4free.py文件里面改接口

**Comment by RockChinQ** [comment]
> > 现在有一个问题，我在acheong08/ChatGPT渠道中添加了gpt3.5普通账号的accesstoken，但是当我用接口调用gpt-4模型时，也能返回结果，给某个渠道设置模型嘛，比如gpt3.5的渠道，当接口请求gpt-4渠道的时候不使用设置为3.5的那个渠道
> 
> gpt4free一直用chatbase那个接口，怎么在gpt4free.py文件里面改接口

目前程序是自动选择gpt4free的可用接口，暂不支持指定g4f使用的接口
