### ISSUE TITLE
404错误，环境安装完成，python版本用了3.10和3.11均出错，请问需要修改什么呢

### ISSUE THREAD

**Issue by dazhizun** [RockChinQ/free-one-api#53]
刷新网页出错提示：
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

![微信截图_20231021152700](https://github.com/RockChinQ/free-one-api/assets/3522824/0dd16f3c-cf34-41d8-8805-349ace60b59b)
![微信截图_20231021152822](https://github.com/RockChinQ/free-one-api/assets/3522824/1bf6c69d-f064-46b8-9542-f610b5a8c8b2)

**Comment by RockChinQ** [comment]
手动部署的话，你编译了前端页面吗？可以看看教程中的内容

先执行

```bash
cd web
npm install
npm run build
```

**Comment by dazhizun** [comment]
哦哦，还需要编译前端页面呀，我研究下，谢谢哈
