### ISSUE TITLE
chatgpt-next-web无法使用

### ISSUE THREAD

**Issue by xiaozhou26** [RockChinQ/free-one-api#59]
使用vercel部署chatgpt-next-web之后无法使用api
![1](https://github.com/RockChinQ/free-one-api/assets/122727418/19e83766-25f5-4044-ab8b-5cdbdccc42e5)
![2](https://github.com/RockChinQ/free-one-api/assets/122727418/f286237c-b9bd-46d1-a8f5-7d86e66242b1)

**Comment by RockChinQ** [comment]
这是没有配置好证书，你nextweb签了ssl然后用https访问的，但是free-one-api没有签证书，或者你为nextweb填写的baseurl没有使用https，你必须保证nextweb和foa都使用http或者https协议。

**Comment by xiaozhou26** [comment]
> 这是没有配置好证书，你nextweb签了ssl然后用https访问的，但是free-one-api没有签证书，或者你为nextweb填写的baseurl没有使用https，你必须保证nextweb和foa都使用http或者https协议。

nextweb是vercel部署的默认https不能用http，foa是服务器docker部署不能用https协议，在cloudflare上开启了ssl的full还是不行，不知道怎么解决

**Comment by xiaozhou26** [comment]
> 这是没有配置好证书，你nextweb签了ssl然后用https访问的，但是free-one-api没有签证书，或者你为nextweb填写的baseurl没有使用https，你必须保证nextweb和foa都使用http或者https协议。

作者你好，bard怎么配置？我配置__Secure-1PSID后还是无法使用

**Comment by RockChinQ** [comment]
> > 这是没有配置好证书，你nextweb签了ssl然后用https访问的，但是free-one-api没有签证书，或者你为nextweb填写的baseurl没有使用https，你必须保证nextweb和foa都使用http或者https协议。
> 
> 作者你好，bard怎么配置？我配置__Secure-1PSID后还是无法使用

bard这个token经常会无效，可以尝试重新登录google然后重新取这个值
