### ISSUE TITLE
I can't create channels

### ISSUE THREAD

**Issue by luiso198** [RockChinQ/free-one-api#63]
Hi!

I can't do anything! it asks me for a token, I don't know which token to write.

![hi](https://github.com/RockChinQ/free-one-api/assets/130424679/cb51f324-6d4b-4aa7-98bd-ec499b240574)

**Comment by RockChinQ** [comment]
The initial token is '12345678', you can change it in `config.yaml`.

**Comment by RockChinQ** [comment]
See documentation of config file at: https://rockchinq.github.io/free-one-api/#/en/Config

**Comment by luiso198** [comment]
Thanks, I am testing the api in a python script. can I choose the provider? Example, "provider": "g4f.Provider.Bing",

**Comment by RockChinQ** [comment]
> Thanks, I am testing the api in a python script. can I choose the provider? Example, "provider": "g4f.Provider.Bing",

Currently not supported this feature.

**Comment by luiso198** [comment]
Is there a way to choose the Provider?
Can it be configured in the panel and how can I do it?

Thank you.

**Comment by RockChinQ** [comment]
> Is there a way to choose the Provider? Can it be configured in the panel and how can I do it?
> 
> Thank you.

No, you can not change the Provider of g4f at current version.
