### ISSUE TITLE
test channel fail 

### ISSUE THREAD

**Issue by linyours** [RockChinQ/free-one-api#66]

**Comment by linyours** [comment]
<img width="1375" alt="image" src="https://github.com/RockChinQ/free-one-api/assets/71416178/c0584fc3-2886-4043-ada6-d7c093f1ab79">

**Comment by linyours** [comment]
<img width="1375" alt="image" src="https://github.com/RockChinQ/free-one-api/assets/71416178/28ddb7d4-9bad-4f3d-91c0-ecb7d7071527">

**Comment by amit4317** [comment]
same issue
