### ISSUE TITLE
v1/chat/completion接口不能用

### ISSUE THREAD

**Issue by jsxupeng** [RockChinQ/free-one-api#67]

**Comment by RockChinQ** [comment]
请详细描述问题并提供配置相关截图以及控制台输出错误

**Comment by jsxupeng** [comment]
> 请详细描述问题并提供配置相关截图以及控制台输出错误

或者说是对外提供的接口地址是什么？是ip:port/v1/chat/completions?

**Comment by RockChinQ** [comment]
可以参考一下文档这里的curl命令测试接口 https://rockchinq.github.io/free-one-api/#/zh-CN/Usage?id=%e6%b5%8b%e8%af%95

**Comment by jsxupeng** [comment]
> > 请详细描述问题并提供配置相关截图以及控制台输出错误
> 
> 或者说是对外提供的接口地址是什么？是ip:port/v1/chat/completions?

![屏幕截图 2023-11-10 213153](https://github.com/RockChinQ/free-one-api/assets/130374594/c90f8a0e-27db-46fd-994e-f6e331a40959)
接口不能访问

**Comment by RockChinQ** [comment]
确认一下有没有正常启动，或者用postman之类的工具发post请求

**Comment by jsxupeng** [comment]
> postman

docker部署，管理页能访问
![屏幕截图 2023-11-10 213554](https://github.com/RockChinQ/free-one-api/assets/130374594/b4ae9518-ca01-4207-86cd-9441899a95d9)

**Comment by RockChinQ** [comment]
不要用浏览器访问，用postman发post请求，具体使用方法请查看OpenAI文档 https://platform.openai.com/docs/api-reference/chat/create

**Comment by jsxupeng** [comment]
> 不要用浏览器访问，用postman发post请求，具体使用方法请查看OpenAI文档 https://platform.openai.com/docs/api-reference/chat/create

![屏幕截图 2023-11-10 215414](https://github.com/RockChinQ/free-one-api/assets/130374594/7d7286aa-73c0-46af-8f3a-681d6a0c0ed7)

这样ok了，
