### ISSUE TITLE
怎么设置bard的渠道？

### ISSUE THREAD

**Issue by luoysuan** [RockChinQ/free-one-api#68]

**Comment by luoysuan** [comment]
刚刚试了一下，bard的好像也失效了

**Comment by johnd0e** [comment]
I have tried Bard-API and found that I need to pass cookies in order to make it working.

@RockChinQ 

Please enable configuration.

**Comment by RockChinQ** [comment]
Due to Bard's blocking policy for China, I can't access Bard, even using proxy and dummy accounts. Looking for contributors now.
