### ISSUE TITLE
通义千问的api好像已经失效了

### ISSUE THREAD

**Issue by luoysuan** [RockChinQ/free-one-api#69]

**Comment by RockChinQ** [comment]
那个作者号被封了

**Comment by luoysuan** [comment]
> 那个作者号被封了

后续会考虑把这块重新写吗 大佬

**Comment by RockChinQ** [comment]
看情况，我也不确定，最近比较忙

**Comment by luoysuan** [comment]
> 看情况，我也不确定，最近比较忙

好的大佬，可以建个群，一起为开源出把力

**Comment by RockChinQ** [comment]
> > 看情况，我也不确定，最近比较忙
> 
> 好的大佬，可以建个群，一起为开源出把力

可以提pr贡献代码

**Comment by RockChinQ** [comment]
<img width="420" alt="image" src="https://github.com/RockChinQ/free-one-api/assets/45992437/584b3fc7-c253-49ed-8d0d-23a9c8a3672c">

![image](https://github.com/RockChinQ/free-one-api/assets/45992437/859fb2ef-4687-4516-b2ba-a2fe16e1be51)

revTongYi 已可用，新的项目地址在 https://github.com/leeeduke/revTongYi

**Comment by luoysuan** [comment]
大佬牛逼&nbsp;


无妻徒刑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junyan ***@***.***&gt;; 
发送时间: 2024年1月23日(星期二) 中午11:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RockChinQ/free-one-api] 通义千问的api好像已经失效了 (Issue #69)





 image.png (view on web) 
image.png (view on web)
 
revTongYi 已可用，新的项目地址在 https://github.com/leeeduke/revTongYi

**Comment by jxyk2007** [comment]
如何使用qianwen的模型？
