### ISSUE TITLE
能给一个用来搭建代理的教程

### ISSUE THREAD

**Issue by luoysuan** [RockChinQ/free-one-api#71]
首页上的地址没有教程，原作者好像归档了
![image](https://github.com/RockChinQ/free-one-api/assets/51365362/2cb13dbe-16d9-4b12-a808-579023c00f3c)

**Comment by RockChinQ** [comment]
这个项目的README也很直白的，很基础的英语，直接运行就可以了。  
顺便，revChatGPT 目前处于不可用状态。

**Comment by luoysuan** [comment]
> 这个项目的README也很直白的，很基础的英语，直接运行就可以了。 顺便，revChatGPT 目前处于不可用状态。

绷不住了，还想试试chatgpt的，现在revChatGPT没法用的话都没东西能白嫖了。。

**Comment by RockChinQ** [comment]
目前基本上只有gpt4free能长期用用

**Comment by luoysuan** [comment]
> 目前基本上只有gpt4free能长期用用

gtp4free用的第三方的，怕数据泄露不敢用。。
