### ISSUE TITLE
ChatGPT not working? 

### ISSUE THREAD

**Issue by LuisBeOnline** [RockChinQ/free-one-api#73]

**Comment by RockChinQ** [comment]
Yes, the dependency [acheong08/ChatGPT](https://github.com/acheong08/ChatGPT) is unmaintained.

**Comment by johnd0e** [comment]
@RockChinQ 
You could replace it with some other project, e.g. https://github.com/Simatwa/WebChatGPT

**Comment by johnd0e** [comment]
BTW, I've just checked https://github.com/acheong08/ChatGPT, and it still works for me.
But you absolutely need to set proper reverse proxy url!
As I found, one provided in docs does not work: `https://chatproxy.rockchin.top/api/` - bad.

**Comment by RockChinQ** [comment]
## Recovered

- `https://chatproxy.rockchin.top/api/` is available now, using https://github.com/flyingpot/chatgpt-proxy
- See https://github.com/flyingpot/chatgpt-proxy

**Comment by RockChinQ** [comment]
> @RockChinQ You could replace it with some other project, e.g. https://github.com/Simatwa/WebChatGPT

I will check it.
