### ISSUE TITLE
backend接口不支持gpt4模型，

### ISSUE THREAD

**Issue by xupeng19881010** [RockChinQ/free-one-api#78]
backend接口不支持gpt4模型，

**Comment by RockChinQ** [comment]
怎么个不支持法，详细描述一下

**Comment by jsxupeng** [comment]
![QQ图片20240125085049](https://github.com/RockChinQ/free-one-api/assets/130374594/f881ae50-7783-4723-aa93-a187ee2868e2)

![QQ图片20240125085138](https://github.com/RockChinQ/free-one-api/assets/130374594/a41c6cba-cde3-4151-9382-10b54605ced5)
所以接口都是通过请求gpt-3.5-turbo这个模型，所以请求gpt4也被 重定向到gpt-3.5-turbo，导致无法请求gpt4

**Comment by RockChinQ** [comment]
#20
