### ISSUE TITLE
The suffix/v1/chat/completion is incorrect, displaying 404

### ISSUE THREAD

**Issue by ZaiQi-zq** [RockChinQ/free-one-api#81]
The suffix/v1/chat/completion is incorrect, displaying 404

**Comment by ZaiQi-zq** [comment]
/v1/chat/completions

**Comment by RockChinQ** [comment]
that's `/v1/chat/completions`

**Comment by RockChinQ** [comment]
Access this path through browser will get 404 indeed, this can only be used by POST method.

**Comment by ZaiQi-zq** [comment]
OK，Thanks

**Comment by ZaiQi-zq** [comment]
As for the selection of models, I don't see any description in the document

**Comment by ZaiQi-zq** [comment]
Also, is it possible to support multiple accounts? I would like to automatically call the second account when the first one expires

**Comment by ZaiQi-zq** [comment]
I can only initiate the GPT3.5 default model now

**Comment by ZaiQi-zq** [comment]
The log shows the GPT-4 model, but in reality, GPT3.5 is still being called up. I have confirmed that my account has enabled Plus. Thank you

**Comment by RockChinQ** [comment]
#20
