### ISSUE TITLE
添加了qianwen的cookie ，如何通过/v1/chat/completions调用

### ISSUE THREAD

**Issue by jxyk2007** [RockChinQ/free-one-api#87]
添加了qianwen的cookie ，如何通过/v1/chat/completions调用

**Comment by RockChinQ** [comment]
你加了渠道，启用它，然后在apikey那个页面生成一个key，就可以通过标准的 OpenAI ChatCompletions 接口调用了，详细请看文档

**Comment by jxyk2007** [comment]
在qianwen后台并未看到对话记录啊
"model": "gpt-3.5-turbo",  返回的信息是这样的`
data: {"id": "chatcmpl-001QianW7xbKFlwgztQfAD9sU35B5", "object": "chat.completion.chunk", "created": 1709024879, "model": "gpt-3.5-turbo", "choices": [{"index": 0, "delta": {"content": "8"}, "finish_reason": null}]}

data: {"id": "chatcmpl-001QianW7xbKFlwgztQfAD9sU35B5", "object": "chat.completion.chunk", "created": 1709024879, "model": "gpt-3.5-turbo", "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}]}
`    这个信息是gpt返回的吗？还是qianwen ？

**Comment by jxyk2007** [comment]
对话记录不会在 qianwen的https://tongyi.aliyun.com/  web后台看到吗？

**Comment by RockChinQ** [comment]
会自动删除

**Comment by jxyk2007** [comment]
哪里可以设置不删除吗？

**Comment by RockChinQ** [comment]
目前暂时不支持，可以考虑添加一下

**Comment by jxyk2007** [comment]
既然是revTongYi  应该要返回对话id 方便支持连续对话

**Comment by RockChinQ** [comment]
OpenAI 协议中不会传递千问的msgid给调用者，故 free-one-api 没法识别每个请求对应的 千问对话id。目前free-one-api 内部是简单地通过拼接多条历史消息为一条消息，发送给上游以获取回复。
