### ISSUE TITLE
acheong08/ChatGPT GG

### ISSUE THREAD

**Issue by ZaiQi-zq** [RockChinQ/free-one-api#90]
[acheong08/ChatGPT](https://github.com/acheong08/ChatGPT) 似乎已经GG了

**Comment by Gijela** [comment]
> [acheong08/ChatGPT](https://github.com/acheong08/ChatGPT) 似乎已经GG了

貌似是的，测了一下没跑通

**Comment by RockChinQ** [comment]
revChatGPT 前俩月能用已经算烧高香了，其他的我来测测先

**Comment by RockChinQ** [comment]
目前只有 huggingchat revTongYi gpt4free 能用。
